/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dz100.samples.charts.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Chart service. Represents a row in the &quot;DZ_Chart&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.dz100.samples.charts.model.impl.ChartModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.dz100.samples.charts.model.impl.ChartImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Chart
 * @generated
 */
@ProviderType
public interface ChartModel extends BaseModel<Chart> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a chart model instance should use the {@link Chart} interface instead.
	 */

	/**
	 * Returns the primary key of this chart.
	 *
	 * @return the primary key of this chart
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this chart.
	 *
	 * @param primaryKey the primary key of this chart
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the name of this chart.
	 *
	 * @return the name of this chart
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this chart.
	 *
	 * @param name the name of this chart
	 */
	public void setName(String name);

	/**
	 * Returns the year_2015 of this chart.
	 *
	 * @return the year_2015 of this chart
	 */
	public int getYear_2015();

	/**
	 * Sets the year_2015 of this chart.
	 *
	 * @param year_2015 the year_2015 of this chart
	 */
	public void setYear_2015(int year_2015);

	/**
	 * Returns the year_2016 of this chart.
	 *
	 * @return the year_2016 of this chart
	 */
	public int getYear_2016();

	/**
	 * Sets the year_2016 of this chart.
	 *
	 * @param year_2016 the year_2016 of this chart
	 */
	public void setYear_2016(int year_2016);

	/**
	 * Returns the year_2017 of this chart.
	 *
	 * @return the year_2017 of this chart
	 */
	public int getYear_2017();

	/**
	 * Sets the year_2017 of this chart.
	 *
	 * @param year_2017 the year_2017 of this chart
	 */
	public void setYear_2017(int year_2017);

}